### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by Cyberstro** [varchashva/vPrioritizer#1]
My boss saw your presentation on BlackHat, and I'm really excited to see this product. Any ETA on when it might be available?

**Comment by blockanz** [comment]
I'm also curious as to when it will be available.

**Comment by varchashva** [comment]
thanks @Cyberstro & @blockanz. I will make vPrioritizer available by end of Aug, 2020.

**Comment by blockanz** [comment]
> thanks @Cyberstro & @blockanz. I will make vPrioritizer available by end of Aug, 2020.

Any updates on this @varchashva ?

**Comment by varchashva** [comment]
@blockanz @Cyberstro @lsandovalintelicorp - I know, a little late, but here it comes. Check it out and let me know your thoughts. Thanks!
