### ISSUE TITLE
Page not Found

### ISSUE THREAD

**Issue by blockanz** [varchashva/vPrioritizer#3]
Ran docker image and getting the following when connecting to localhost:7777

Page not found (404)

Request: Method: GET
Request URL: http://localhost:7777/

Using the URLconf defined in vPrioritizer.urls, Django tried these URL patterns, in this order:

1. ^admin/
2. ^vp/
The empty path didn't match any of these.

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

Same error also occurs if you run python manage.py runserver 0.0.0.0:7777

**Comment by varchashva** [comment]
@blockanz - Please access using http://localhost:7777/vp. I have updated the "Read Me" as well. let me know how it goes.

thanks for feedback.

**Comment by blockanz** [comment]
Thanks, that part now working.
