### ISSUE TITLE
Error when creating a new project

### ISSUE THREAD

**Issue by blockanz** [varchashva/vPrioritizer#4]
Trying to create a new project.

Click on Create Project, and enter the name of the project I want to create.
When I click + I get the following:

![image](https://user-images.githubusercontent.com/22645955/92297914-2ac76700-ef98-11ea-87de-a432c9e6fb77.png)

**Comment by varchashva** [comment]
@blockanz - I think I understand what's the problem, let me dig into this. thanks for feedback.

**Comment by varchashva** [comment]
hi @blockanz

Have implemented the fix on v1.0 - supported lower & upper characters, numbers and underscore (_) in project name. Please check and do let me know for any query.

If you are using Docker version, just re-run the docker-compose up --build with latest docker-compose file

Thanks!

**Comment by blockanz** [comment]
@varchashva I can confirm that this seems to have been resolved now. Many thanks.

**Comment by varchashva** [comment]
@blockanz - thanks for confirmation!
